webdriver {
    driver = chrome
    autodownload = true
    wait.for.timeout = 10000
    timeouts {
        implicitlywait = 10000
        fluentwait = 10000
    }
}

chrome.switches = """--start-maximized;--remote-allow-origins=*;--test-type;--no-sandbox;--ignore-certificate-errors;--disable-popup-blocking;--incognito;--disable-gpu"""

serenity {
    take.screenshots = FOR_EACH_ACTION
    console.colors = true
    project.name = "Prueba TCS"
    test.root = "com.features"
    tag.failures = "true"
    report.accessibility = true
}
